### ISSUE TITLE
TypeError: fsevents.watch is not a function Error & more

### ISSUE THREAD

**Issue by filippo-fonseca** [microsoft/TypeScript-Website#1391]
**Improvement Idea:**

This may be just me, but there is a problem when I attempt to run the site on my local machine. I receive the following error (again, this may be just me, but others may have this issue, so I thought I'd bring it up):

<img width="1435" alt="Screen Shot 2020-12-02 at 11 04 53" src="https://user-images.githubusercontent.com/48065878/100905915-35f23c00-348e-11eb-9c3a-e4843e155879.png">

This may require a potential fix to the actual modules or perhaps an improvement to the documentation to avoid this issue. Let me know!

**Why:**

This way, we allow a more cohesive environment for people to contribute to the TS website's development.

**Alternative ideas:**

Not that I can think of (besides maybe improving modules and the TypeError or docs to avoid this issue). This may be just in my local machine or perhaps installation I didn't follow properly, but I thought I'd bring it up.

**Comment by orta** [comment]
Is it possible you're maybe using an older version of node? We support node 13 and up on the site

**Comment by kevinmlewis** [comment]
I get the same error and am running node 16.  

```
`MREM82EEECAD:nodejs kevin.lewis$ npm start

> msteams-nodejs-hello-world@1.0.0 start
> nodemon --exec babel-node src/app.js

[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node src/app.js`
/Users/kevin.lewis/Documents/MSTeams/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/nodemon/node_modules/chokidar/lib/fsevents-handler.js:93
  const stop = fsevents.watch(path, callback);
                        ^

TypeError: fsevents.watch is not a function
    at createFSEventsInstance (/Users/kevin.lewis/Documents/MSTeams/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/nodemon/node_modules/chokidar/lib/fsevents-handler.js:93:25)
    at setFSEventsListener (/Users/kevin.lewis/Documents/MSTeams/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/nodemon/node_modules/chokidar/lib/fsevents-handler.js:148:16)
    at FsEventsHandler._watchWithFsEvents (/Users/kevin.lewis/Documents/MSTeams/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/nodemon/node_modules/chokidar/lib/fsevents-handler.js:352:18)
    at FsEventsHandler.initWatch (/Users/kevin.lewis/Documents/MSTeams/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/nodemon/node_modules/chokidar/lib/fsevents-handler.js:429:23)
    at FsEventsHandler._addToFsEvents (/Users/kevin.lewis/Documents/MSTeams/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/nodemon/node_modules/chokidar/lib/fsevents-handler.js:518:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
```

**Comment by diegofss11** [comment]
Also having the same issue when updating from node 14 to 16. Any updates?

**Comment by rvangala936** [comment]
I have the same error - 
/node_modules/watchpack/node_modules/chokidar/lib/fsevents-handler.js:93
  const stop = fsevents.watch(path, callback);
                        ^
TypeError: fsevents.watch is not a function

Here is my ENV:
Angular CLI: **8.1.3**
Node: **16.13.2**
OS: darwin x64
Angular: **8.1.3**
